# ==========================================
# PRODUCTION CLOUD DATABASE CONFIGURATION (POSTGRESQL)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# REAL GMAIL SENDING ENGINE CONFIGURATION
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tholkappiyan.vst@gmail.com
spring.mail.password=sbdvvlowzowqnrvy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# DYNAMIC SYSTEM CONFIGURATION
# ==========================================
# This environment variable links back to your Render web service URL 
app.base.url=${APP_BASE_URL}
